### ISSUE TITLE
Bloccare effetti nativi armature e oggetti

### ISSUE THREAD

**Issue by goldr31** [ForgottenWorld/FWBlocker#1]
**Is your feature request related to a problem? Please describe.**
Abbiamo bisogno di bloccare anche gli effetti nativi di armature e oggetti.

**Describe the solution you'd like**
Un comando, come gli altri, per bloccarli.

**Describe alternatives you've considered**
Una modifica permanente nel server.

**Additional context**
Necessario per bloccare anti knockback nell'armatura di netherite.

**Comment by Filocava99** [comment]
Added config option in the 89c146ce8a5ab482b75a3de42dff1706e7423751 commit
